version: '3.8'

services:
  xpd-bot:
    image: node:latest
    container_name: xpd-conf-bot
    working_dir: /app
    volumes:
      - ./bot:/app
      - db-volume:/db
    command: "npm start"
  
  xpd-api:
    image: node:latest
    container_name: xpd-conf-api
    working_dir: /app
    ports:
      - "7777:7777"
    volumes:
      - ./api:/app
      - db-volume:/db
    command: "npm start"

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      device: /root/xpd-conf-bot
      o: bind
