version: '3.8'

services:
  xpd-bot:
    image: node:latest
    container_name: xpd-conf-bot
    working_dir: /app
    volumes:
      - ./bot:/app
      - db-volume:/db
    command: "npm start"
    networks:
      xpd-network:
        ipv4_address: '172.19.0.2'
  
  xpd-api:
    image: node:latest
    container_name: xpd-conf-api
    working_dir: /app
    ports:
      - "7777:7777"
    volumes:
      - ./api:/app
      - db-volume:/db
    command: "npm start"
    networks:
      xpd-network:
        ipv4_address: '172.19.0.3'

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      device: /root/xpd-conf-bot
      o: bind

networks:
  xpd-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1